spring:
  application:
    name: card-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/madis_db?schema=public}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:poc}
    password: ${SPRING_DATASOURCE_PASSWORD:poc2025}
    hikari:
      minimum-idle: 2              # Keep at least 5 idle connections
      maximum-pool-size: 5        # Prevent excessive DB connections per service
      idle-timeout: 30000          # Close idle connections after 30s
      max-lifetime: 1800000        # Recycle connections every 30 min
      connection-timeout: 30000  
  jackson:
    default-property-inclusion: NON_EMPTY
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
  cloud:
    discovery:
      enabled: true

info:
  app:
    name: ${spring.application.name}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/} # Replace with Eureka server URL
    register-with-eureka: true  # Register this service with Eureka
    fetch-registry: true        # Fetch registry to discover other services
  instance:
    lease-renewal-interval-in-seconds: 30  # Frequency of heartbeat
    lease-expiration-duration-in-seconds: 90 # Expiration if no heartbeat
    prefer-ip-address: true
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:card-service.madisgroup.local}
    hostname: ${HOSTNAME:card-service.madisgroup.local} 



springdoc:
  api-docs:
    version: OPENAPI_3_0
    path: /v3/api-docs # OpenAPI docs endpoint for this service
  swagger-ui:
    path: /swagger-ui.html # Swagger UI for this service

management:
  endpoint:
    health:
      access: unrestricted
      show-details: always
    metrics:
      access: unrestricted
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors.allowed-origins: true

logging:
  level:
    root: ERROR
    '[com.madisfinance.mansacardservice]': DEBUG
    '[org.springframework.web]': ERROR
server:
  port: ${PORT:8083}
