spring:
  application:
    name: mansacard-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/madis_db?schema=public}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:poc}
    password: ${SPRING_DATASOURCE_PASSWORD:poc2025}
  jackson:
    default-property-inclusion: NON_EMPTY
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    
info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        loggerLevel: basic
  discovery:
    enabled: true  # Enables Feign to use Consul for service discovery

springdoc:
  api-docs:
    version: OPENAPI_3_0
    path: /v3/api-docs # OpenAPI docs endpoint for this service
  swagger-ui:
    path: /swagger-ui.html # Swagger UI for this service

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors.allowed-origins: true

logging:
  level:
    root: ERROR
    '[com.madisfinance.mansacardservice]': INFO
    '[org.springframework.web]': ERROR
server:
  port: ${PORT:8081}
