spring:
  application:
    name: mansacard-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/madisdb?schema=public}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:5teevyclear!}
  jackson:
    default-property-inclusion: NON_EMPTY
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: false
  cloud:
    discovery:
      client:
        simple:
          enabled: false # Disable simple discovery client
      aws:
        enabled: true  # Enable AWS-specific discovery
    loadbalancer:
      ribbon:
        enabled: true # Enable Ribbon-based load balancing (optional)
info:
  app:
    name: ${spring.application.name}

cloud:
  aws:
    region:
      static: eu-north-1 # Replace with your AWS region
    discovery:
      enabled: true # Enable service discovery
    cloud-map:
      namespace: madis-ns-02  # Replace with your AWS Cloud Map namespace name
      discovery-service-id: mansacard-service # Replace with the ID of your service registered in Cloud Map
      health-check:
        enabled: true # Optional: Enable health check for service instances

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
  discovery:
    enabled: true  # Enables Feign to use Consul for service discovery

springdoc:
  api-docs:
    version: OPENAPI_3_0
    path: /v3/api-docs # OpenAPI docs endpoint for this service
  swagger-ui:
    path: /swagger-ui.html # Swagger UI for this service

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors.allowed-origins: true

logging:
  level:
    root: ERROR
    com.madisfinance.mansacardservice: INFO
    org.springframework.web: ERROR
server:
  port: ${PORT:8080}
